package com.sinter.daily;
import android.app.*;import android.appwidget.*;import android.content.*;import android.graphics.Color;import android.graphics.Typeface;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.view.*;import android.widget.*;import java.util.*;
public class MainActivity extends Activity {
 final int ink=Color.rgb(48,43,50),purple=Color.rgb(100,67,117),muted=Color.rgb(138,128,119),cream=Color.rgb(255,248,236);int current;LinearLayout body;final Handler handler=new Handler(Looper.getMainLooper());final Runnable tick=new Runnable(){public void run(){if(Store.current(MainActivity.this)!=current)render();handler.postDelayed(this,30000);}};
 int dp(int n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
 TextView text(String s,int size,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setLineSpacing(dp(5),1);return t;}
 GradientDrawable bg(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
 void gap(LinearLayout l,int h){Space s=new Space(this);l.addView(s,new LinearLayout.LayoutParams(1,dp(h)));}
 Button button(String s,Runnable r){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(purple);b.setTextSize(14);b.setBackground(bg(0xffece3ef,14));b.setMinHeight(dp(48));b.setPadding(dp(8),dp(8),dp(8),dp(8));b.setOnClickListener(v->r.run());return b;}
 void row(LinearLayout parent,Button...bs){LinearLayout row=new LinearLayout(this);for(Button b:bs){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(52),1);p.setMargins(dp(3),0,dp(3),0);row.addView(b,p);}parent.addView(row);}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(0xfff3eee6);getWindow().setNavigationBarColor(0xfff3eee6);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);}
 @Override public void onResume(){super.onResume();render();handler.postDelayed(tick,30000);}
 @Override public void onPause(){handler.removeCallbacks(tick);super.onPause();}
 void render(){
  current=Store.current(this);QuoteWidget.refresh(this);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setBackgroundColor(0xfff3eee6);body=new LinearLayout(this);body.setOrientation(1);body.setPadding(dp(24),dp(24),dp(24),dp(32));scroll.addView(body);setContentView(scroll);
  if(Build.VERSION.SDK_INT>=35)scroll.setOnApplyWindowInsetsListener((v,in)->{android.graphics.Insets bar=in.getInsets(WindowInsets.Type.systemBars());v.setPadding(bar.left,bar.top,bar.right,bar.bottom);return in;});
  TextView label=text("DAILY WISDOM  /  一日一句",12,purple);label.setLetterSpacing(.12f);body.addView(label);gap(body,12);TextView title=text("让一句话，陪你过一天。",26,ink);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);body.addView(title);gap(body,8);body.addView(text("500 条人生建议 · 每天读一点，慢慢体会",13,muted));gap(body,28);
  LinearLayout card=new LinearLayout(this);card.setOrientation(1);card.setPadding(dp(24),dp(24),dp(24),dp(24));card.setBackground(bg(cream,24));body.addView(card);
  card.addView(text(Store.day().replace('-','.')+"  /  "+(Store.held(this)?"这一句，继续陪你":"今天的偶遇"),12,purple));gap(card,20);
  TextView quote=text(Store.quote(this,current).optString("text"),24,ink);quote.setTypeface(Typeface.create("serif",Typeface.NORMAL));quote.setTextIsSelectable(true);quote.setLineSpacing(dp(10),1.15f);card.addView(quote);gap(card,24);card.addView(text("《宝贵的人生建议》",13,purple));card.addView(text(Store.source(this,current),11,muted));gap(card,12);card.addView(text(String.format(Locale.CHINA,"%03d / 500",current+1),11,muted));gap(body,20);
  row(body,button("换一句",()->{Store.next(this);render();}),button(Store.favorite(this,current)?"♥ 已收藏":"♡ 收藏",()->{Store.toggle(this,current);render();}),button(Store.held(this)?"恢复更新":"让它停留",()->{Store.hold(this);render();}));gap(body,12);
  body.addView(button("＋ 放到手机桌面",()->pin()));gap(body,12);body.addView(button("我的收藏  ·  "+Store.favorites(this).size(),()->favorites()));gap(body,22);
  body.addView(text(Store.held(this)?"已暂停每日换句。点击「恢复更新」继续；「换一句」也会结束停留。":"每天换一条；同一天保持不变。随机读完一轮再重复，也可以随时手动换一句。",13,muted));gap(body,16);TextView help=text("安装与使用说明  ↗",13,purple);help.setPadding(0,dp(10),0,dp(10));help.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("把一句话放到桌面").setMessage("点击「放到手机桌面」，按系统提示添加。如果没有弹窗，回到桌面，长按空白处 → 小组件／窗口小工具 → 一日一句。推荐 4×2，长句可放大到 4×3，可长按调整大小。长句显示不全时，点「展开全文」。\n\n应用离线工作，无账号、无广告、无联网权限。每日更新可能因系统省电策略延迟；打开应用即可刷新。需要时可在手机设置中允许本应用后台运行。\n\n书摘来自你提供的 PDF，凯文·凯利著、刘波译。编号依照文件顺序编排，页码为 PDF 页序，非纸书页码。").setPositiveButton("知道了",null).show());body.addView(help);
 }
 void pin(){AppWidgetManager m=AppWidgetManager.getInstance(this);if(m.isRequestPinAppWidgetSupported()){m.requestPinAppWidget(new ComponentName(this,QuoteWidget.class),null,null);}else new AlertDialog.Builder(this).setTitle("手动添加小组件").setMessage("回到手机桌面 → 长按空白处 → 小组件／窗口小工具 → 找到「一日一句」并拖到桌面。").setPositiveButton("好的",null).show();}
 void favorites(){ArrayList<Integer> ids=new ArrayList<>();for(String s:Store.favorites(this))ids.add(Integer.parseInt(s));Collections.sort(ids);if(ids.isEmpty()){new AlertDialog.Builder(this).setTitle("收藏夹还是空的").setMessage("遇到触动你的话，点一下「♡ 收藏」，就会留在这里。").setPositiveButton("好",null).show();return;}String[] labels=new String[ids.size()];for(int i=0;i<ids.size();i++){String s=Store.quote(this,ids.get(i)).optString("text");labels[i]=String.format(Locale.CHINA,"%03d  ",ids.get(i)+1)+s;}new AlertDialog.Builder(this).setTitle("我想记住的话").setItems(labels,(d,pos)->showFavorite(ids.get(pos))).setNegativeButton("关闭",null).show();}
 void showFavorite(int id){new AlertDialog.Builder(this).setTitle("第 "+(id+1)+" 条建议").setMessage(Store.quote(this,id).optString("text")+"\n\n"+Store.source(this,id)).setPositiveButton("关闭",null).setNeutralButton("取消收藏",(d,w)->{Store.toggle(this,id);render();}).show();}
}
